/**
 * Mock Data
 * =====================
 * Realistic demo data for the sales video flow.
 * KPI numbers match spec: 124 Overdue, 248 Reactivated, $42,580 Recovered
 */

// --- Dashboard KPIs (Revenue-First) ---
export const dashboardKPIs = {
  revenueRecovered: { value: 42580, trend: "+18%", period: "this quarter" },
  patientsReactivated: { value: 248, trend: "+32%", period: "this quarter" },
  overduePatients: { value: 124, trend: "-8%", period: "vs last month", urgent: true },
  appointmentsRecovered: { value: 186, trend: "+24%", period: "this quarter" },
  potentialRevenueLost: { value: 18450, trend: "-12%", period: "this month" },
  recoverableRevenue: { value: 9200, label: "Actionable now" },
  noShowReduction: { value: 34, unit: "%", trend: "+12%", period: "vs last quarter" },
  treatmentFollowUpRate: { value: 78, unit: "%", trend: "+6%", period: "this month" },
};

// --- Patients ---
export const patients = [
  {
    id: "PT-1001",
    firstName: "Sarah",
    lastName: "Miller",
    email: "sarah.miller@email.com",
    phone: "(555) 123-4567",
    dateOfBirth: "1985-03-15",
    lastVisit: "2025-10-12",
    nextRecall: "2026-04-12",
    status: "overdue",
    treatmentStatus: "Recall Cleaning",
    revenueOpportunity: 180,
    insuranceProvider: "Delta Dental",
    notes: "Prefers morning appointments. Sensitive to cold.",
  },
  {
    id: "PT-1002",
    firstName: "John",
    lastName: "Smith",
    email: "john.smith@email.com",
    phone: "(555) 234-5678",
    dateOfBirth: "1978-07-22",
    lastVisit: "2026-01-15",
    nextRecall: "2026-07-15",
    status: "active",
    treatmentStatus: "Crown (Pending)",
    revenueOpportunity: 1500,
    insuranceProvider: "Cigna",
    notes: "Treatment plan discussed. Waiting for insurance approval.",
  },
  {
    id: "PT-1003",
    firstName: "Emily",
    lastName: "Davis",
    email: "emily.davis@email.com",
    phone: "(555) 345-6789",
    dateOfBirth: "1992-11-08",
    lastVisit: "2026-02-20",
    nextRecall: "2026-08-20",
    status: "treatment-pending",
    treatmentStatus: "Veneer Consultation",
    revenueOpportunity: 2100,
    insuranceProvider: "MetLife",
    notes: "Interested in cosmetic improvements. Follow up next week.",
  },
  {
    id: "PT-1004",
    firstName: "Michael",
    lastName: "Wilson",
    email: "michael.w@email.com",
    phone: "(555) 456-7890",
    dateOfBirth: "1970-05-30",
    lastVisit: "2025-08-15",
    nextRecall: "2026-02-15",
    status: "overdue",
    treatmentStatus: "Root Canal + Crown",
    revenueOpportunity: 3200,
    insuranceProvider: "Aetna",
    notes: "High anxiety patient. Needs sedation options discussed.",
  },
  {
    id: "PT-1005",
    firstName: "Jessica",
    lastName: "Brown",
    email: "jess.brown@email.com",
    phone: "(555) 567-8901",
    dateOfBirth: "1988-09-14",
    lastVisit: "2026-05-01",
    nextRecall: "2026-11-01",
    status: "active",
    treatmentStatus: null,
    revenueOpportunity: 0,
    insuranceProvider: "Blue Cross",
    notes: "Regular patient. No outstanding treatments.",
  },
  {
    id: "PT-1006",
    firstName: "Robert",
    lastName: "Johnson",
    email: "r.johnson@email.com",
    phone: "(555) 678-9012",
    dateOfBirth: "1965-12-03",
    lastVisit: "2025-06-20",
    nextRecall: "2025-12-20",
    status: "overdue",
    treatmentStatus: "Implant Consultation",
    revenueOpportunity: 4500,
    insuranceProvider: "Guardian",
    notes: "Missing #14. Discussed implant options. Needs follow-up.",
  },
  {
    id: "PT-1007",
    firstName: "Amanda",
    lastName: "Garcia",
    email: "amanda.g@email.com",
    phone: "(555) 789-0123",
    dateOfBirth: "1995-01-25",
    lastVisit: "2026-04-10",
    nextRecall: "2026-10-10",
    status: "due-soon",
    treatmentStatus: "Whitening",
    revenueOpportunity: 450,
    insuranceProvider: "United Healthcare",
    notes: "Scheduled for whitening. Excited about results.",
  },
  {
    id: "PT-1008",
    firstName: "David",
    lastName: "Martinez",
    email: "d.martinez@email.com",
    phone: "(555) 890-1234",
    dateOfBirth: "1982-04-17",
    lastVisit: "2026-03-05",
    nextRecall: "2026-09-05",
    status: "no-show",
    treatmentStatus: "Recall Cleaning",
    revenueOpportunity: 180,
    insuranceProvider: "Humana",
    notes: "No-showed last appointment. Attempted contact twice.",
  },
  {
    id: "PT-1009",
    firstName: "Lisa",
    lastName: "Anderson",
    email: "lisa.a@email.com",
    phone: "(555) 901-2345",
    dateOfBirth: "1975-08-09",
    lastVisit: "2025-11-18",
    nextRecall: "2026-05-18",
    status: "overdue",
    treatmentStatus: "Bridge Replacement",
    revenueOpportunity: 2800,
    insuranceProvider: "Delta Dental",
    notes: "Bridge on #3-5 failing. Needs replacement urgently.",
  },
  {
    id: "PT-1010",
    firstName: "James",
    lastName: "Taylor",
    email: "j.taylor@email.com",
    phone: "(555) 012-3456",
    dateOfBirth: "1990-02-28",
    lastVisit: "2026-05-20",
    nextRecall: "2026-11-20",
    status: "active",
    treatmentStatus: null,
    revenueOpportunity: 0,
    insuranceProvider: "Cigna",
    notes: "New patient. First visit completed. Very satisfied.",
  },
  {
    id: "PT-1011",
    firstName: "Patricia",
    lastName: "Thomas",
    email: "p.thomas@email.com",
    phone: "(555) 111-2233",
    dateOfBirth: "1968-06-12",
    lastVisit: "2025-07-30",
    nextRecall: "2026-01-30",
    status: "overdue",
    treatmentStatus: "Periodontal Maintenance",
    revenueOpportunity: 220,
    insuranceProvider: "MetLife",
    notes: "History of periodontal disease. Needs 3-month recalls.",
  },
  {
    id: "PT-1012",
    firstName: "Christopher",
    lastName: "Lee",
    email: "c.lee@email.com",
    phone: "(555) 222-3344",
    dateOfBirth: "1998-10-05",
    lastVisit: "2026-04-22",
    nextRecall: "2026-10-22",
    status: "treatment-pending",
    treatmentStatus: "Wisdom Tooth Extraction",
    revenueOpportunity: 800,
    insuranceProvider: "Aetna",
    notes: "Impacted #32. Referred for extraction. Awaiting scheduling.",
  },
  {
    id: "PT-1013",
    firstName: "Nancy",
    lastName: "Harris",
    email: "nancy.h@email.com",
    phone: "(555) 333-4455",
    dateOfBirth: "1972-03-20",
    lastVisit: "2025-09-10",
    nextRecall: "2026-03-10",
    status: "overdue",
    treatmentStatus: "Recall Cleaning",
    revenueOpportunity: 180,
    insuranceProvider: "Guardian",
    notes: "Reliable patient. Overdue likely due to schedule conflict.",
  },
  {
    id: "PT-1014",
    firstName: "Daniel",
    lastName: "Clark",
    email: "dan.clark@email.com",
    phone: "(555) 444-5566",
    dateOfBirth: "1985-12-15",
    lastVisit: "2026-01-08",
    nextRecall: "2026-07-08",
    status: "due-soon",
    treatmentStatus: null,
    revenueOpportunity: 180,
    insuranceProvider: "Blue Cross",
    notes: "Due for recall next month.",
  },
  {
    id: "PT-1015",
    firstName: "Karen",
    lastName: "Lewis",
    email: "karen.l@email.com",
    phone: "(555) 555-6677",
    dateOfBirth: "1960-07-08",
    lastVisit: "2025-04-15",
    nextRecall: "2025-10-15",
    status: "overdue",
    treatmentStatus: "Denture Reline",
    revenueOpportunity: 650,
    insuranceProvider: "Humana",
    notes: "Lower denture needs reline. Patient concerned about cost.",
  },
  {
    id: "PT-1016",
    firstName: "Kevin",
    lastName: "Walker",
    email: "k.walker@email.com",
    phone: "(555) 666-7788",
    dateOfBirth: "1993-05-22",
    lastVisit: "2026-05-15",
    nextRecall: "2026-11-15",
    status: "reactivated",
    treatmentStatus: null,
    revenueOpportunity: 0,
    insuranceProvider: "United Healthcare",
    notes: "Reactivated after 18-month gap. Back on regular schedule.",
  },
  {
    id: "PT-1017",
    firstName: "Sandra",
    lastName: "Hall",
    email: "s.hall@email.com",
    phone: "(555) 777-8899",
    dateOfBirth: "1980-11-30",
    lastVisit: "2025-12-05",
    nextRecall: "2026-06-05",
    status: "overdue",
    treatmentStatus: "Recall Cleaning",
    revenueOpportunity: 180,
    insuranceProvider: "Principal",
    notes: "Called twice, no response. Try text message.",
  },
  {
    id: "PT-1018",
    firstName: "Brian",
    lastName: "Young",
    email: "brian.y@email.com",
    phone: "(555) 888-9900",
    dateOfBirth: "1977-09-18",
    lastVisit: "2026-02-14",
    nextRecall: "2026-08-14",
    status: "active",
    treatmentStatus: "Night Guard",
    revenueOpportunity: 350,
    insuranceProvider: "Sun Life",
    notes: "Bruxism. Night guard ordered. Follow up in 2 weeks.",
  },
  {
    id: "PT-1019",
    firstName: "Michelle",
    lastName: "King",
    email: "m.king@email.com",
    phone: "(555) 999-0011",
    dateOfBirth: "1987-02-14",
    lastVisit: "2025-05-20",
    nextRecall: "2025-11-20",
    status: "no-show",
    treatmentStatus: "Filling + Crown",
    revenueOpportunity: 1200,
    insuranceProvider: "Delta Dental",
    notes: "No-showed twice. High value patient. Personal outreach needed.",
  },
  {
    id: "PT-1020",
    firstName: "Steven",
    lastName: "Wright",
    email: "s.wright@email.com",
    phone: "(555) 100-2200",
    dateOfBirth: "1955-08-25",
    lastVisit: "2026-03-28",
    nextRecall: "2026-09-28",
    status: "treatment-pending",
    treatmentStatus: "Full Mouth Restoration",
    revenueOpportunity: 8500,
    insuranceProvider: "Cigna",
    notes: "Comprehensive treatment plan presented. Discussing financing.",
  },
];

// --- Visit History (for patient profile) ---
export const visitHistory = [
  { date: "2026-05-20", type: "Cleaning & Exam", provider: "Jennifer Adams, RDH", notes: "All clear. Next recall in 6 months.", cost: 180 },
  { date: "2026-02-14", type: "Night Guard Delivery", provider: "Dr. Sarah Chen", notes: "Night guard delivered. Fit adjusted. Patient comfortable.", cost: 350 },
  { date: "2025-11-18", type: "Crown Prep #14", provider: "Dr. Sarah Chen", notes: "Crown prep completed. Temp placed. Lab turnaround 2 weeks.", cost: 1200 },
  { date: "2025-10-12", type: "Cleaning & Exam", provider: "Jennifer Adams, RDH", notes: "Moderate calculus. Recommended more frequent flossing.", cost: 180 },
  { date: "2025-07-30", type: "Emergency Visit", provider: "Dr. Michael Torres", notes: "Fractured cusp #14. Treatment plan for crown.", cost: 150 },
  { date: "2025-04-15", type: "Cleaning & Exam", provider: "Jennifer Adams, RDH", notes: "Routine. No issues found.", cost: 180 },
];

// --- Communication Timeline ---
export const communicationTimeline = [
  { date: "2026-06-01", type: "sms", direction: "outbound", message: "Hi Sarah, you're overdue for your cleaning! Call us at (555) 234-5678 to schedule.", status: "delivered" },
  { date: "2026-05-25", type: "email", direction: "outbound", message: "Recall Reminder: Your 6-month cleaning is overdue", status: "opened" },
  { date: "2026-05-20", type: "call", direction: "inbound", message: "Patient called to ask about appointment availability. Left voicemail.", status: "completed" },
  { date: "2026-04-12", type: "sms", direction: "outbound", message: "Reminder: Your recall appointment is coming up. Reply BOOK to schedule.", status: "delivered" },
  { date: "2026-03-01", type: "email", direction: "outbound", message: "Bright Smile Newsletter — Spring Cleaning Special", status: "opened" },
];

// --- Activity Feed ---
export const recentActivity = [
  { id: 1, type: "reminder_sent", patient: "James R.", method: "SMS", time: "10 mins ago" },
  { id: 2, type: "appointment_booked", patient: "Emma L.", method: "Front Desk", time: "1 hour ago" },
  { id: 3, type: "patient_reactivated", patient: "Robert K.", method: "Email Campaign", time: "2 hours ago" },
  { id: 4, type: "treatment_accepted", patient: "Lisa A.", method: "Portal", time: "3 hours ago", value: 2800 },
  { id: 5, type: "no_show", patient: "David M.", method: "Auto-detected", time: "4 hours ago" },
  { id: 6, type: "sync_completed", patient: null, method: "System", time: "4 hours ago" },
];

// --- Reactivation Campaigns ---
export const campaigns = [
  {
    id: "camp-1",
    name: "Overdue 6+ Months",
    status: "active",
    targetCount: 124,
    potentialRevenue: 21400,
    expectedReactivations: 28,
    expectedAppointments: 22,
    expectedRevenue: 4500,
    sentCount: 96,
    openRate: 68,
    responseRate: 24,
    bookedCount: 18,
    startDate: "2026-05-01",
  },
  {
    id: "camp-2",
    name: "Treatment Plan Follow-Up",
    status: "active",
    targetCount: 45,
    potentialRevenue: 67200,
    expectedReactivations: 12,
    expectedAppointments: 10,
    expectedRevenue: 18500,
    sentCount: 45,
    openRate: 72,
    responseRate: 31,
    bookedCount: 8,
    startDate: "2026-04-15",
  },
  {
    id: "camp-3",
    name: "No-Show Recovery",
    status: "paused",
    targetCount: 32,
    potentialRevenue: 5760,
    expectedReactivations: 8,
    expectedAppointments: 6,
    expectedRevenue: 1080,
    sentCount: 20,
    openRate: 55,
    responseRate: 15,
    bookedCount: 3,
    startDate: "2026-05-10",
  },
  {
    id: "camp-4",
    name: "New Patient Welcome Series",
    status: "active",
    targetCount: 18,
    potentialRevenue: 3240,
    expectedReactivations: null,
    expectedAppointments: 15,
    expectedRevenue: 2700,
    sentCount: 18,
    openRate: 85,
    responseRate: 44,
    bookedCount: 12,
    startDate: "2026-03-01",
  },
];

// --- Recall Workflows ---
export const recallWorkflows = [
  {
    id: "wf-1",
    name: "Standard 6-Month Recall",
    active: true,
    steps: [
      { id: "s1", type: "trigger", label: "Visit Completed", icon: "CheckCircle" },
      { id: "s2", type: "wait", label: "Wait 5 Months", duration: "5 months", icon: "Clock" },
      { id: "s3", type: "action", label: "Send Email Reminder", channel: "email", icon: "Mail" },
      { id: "s4", type: "wait", label: "Wait 7 Days", duration: "7 days", icon: "Clock" },
      { id: "s5", type: "condition", label: "Appointment Booked?", icon: "GitBranch" },
      { id: "s6", type: "action", label: "Send SMS Follow-Up", channel: "sms", icon: "MessageSquare" },
      { id: "s7", type: "wait", label: "Wait 7 Days", duration: "7 days", icon: "Clock" },
      { id: "s8", type: "action", label: "Notify Front Desk", channel: "internal", icon: "Bell" },
    ],
  },
  {
    id: "wf-2",
    name: "Overdue Patient Recovery",
    active: true,
    steps: [
      { id: "s1", type: "trigger", label: "Patient Becomes Overdue", icon: "AlertTriangle" },
      { id: "s2", type: "action", label: "Send Personalized Email", channel: "email", icon: "Mail" },
      { id: "s3", type: "wait", label: "Wait 3 Days", duration: "3 days", icon: "Clock" },
      { id: "s4", type: "action", label: "Send SMS with Booking Link", channel: "sms", icon: "MessageSquare" },
      { id: "s5", type: "wait", label: "Wait 5 Days", duration: "5 days", icon: "Clock" },
      { id: "s6", type: "condition", label: "Response Received?", icon: "GitBranch" },
      { id: "s7", type: "action", label: "Personal Phone Call", channel: "call", icon: "Phone" },
      { id: "s8", type: "action", label: "Add to Reactivation Campaign", channel: "internal", icon: "Target" },
    ],
  },
  {
    id: "wf-3",
    name: "No-Show Follow-Up",
    active: false,
    steps: [
      { id: "s1", type: "trigger", label: "Patient No-Shows", icon: "UserX" },
      { id: "s2", type: "wait", label: "Wait 1 Hour", duration: "1 hour", icon: "Clock" },
      { id: "s3", type: "action", label: "Send Rescheduling SMS", channel: "sms", icon: "MessageSquare" },
      { id: "s4", type: "wait", label: "Wait 2 Days", duration: "2 days", icon: "Clock" },
      { id: "s5", type: "action", label: "Send Email with Online Booking", channel: "email", icon: "Mail" },
      { id: "s6", type: "wait", label: "Wait 5 Days", duration: "5 days", icon: "Clock" },
      { id: "s7", type: "action", label: "Notify Staff for Personal Outreach", channel: "internal", icon: "Bell" },
    ],
  },
];

// --- Message Templates ---
export const messageTemplates = [
  {
    id: "tpl-1",
    name: "6-Month Recall Reminder",
    type: "sms",
    category: "recall",
    subject: null,
    body: "Hi {{firstName}}, it's time for your 6-month cleaning at {{clinicName}}! Call us at {{phone}} or reply BOOK to schedule. We look forward to seeing you! 😊",
  },
  {
    id: "tpl-2",
    name: "Overdue Patient Email",
    type: "email",
    category: "recall",
    subject: "We Miss You at {{clinicName}}!",
    body: "Dear {{firstName}},\n\nWe noticed it's been a while since your last visit. Regular dental care is essential for maintaining your beautiful smile.\n\nWe'd love to see you again! Click below to schedule your appointment at a time that works for you.\n\n[Schedule Now]\n\nWarm regards,\n{{dentistName}} & Team",
  },
  {
    id: "tpl-3",
    name: "No-Show Rescheduling",
    type: "sms",
    category: "follow-up",
    subject: null,
    body: "Hi {{firstName}}, we missed you at your appointment today at {{clinicName}}. No worries! Reply BOOK to reschedule, or call us at {{phone}}. We're here for you!",
  },
  {
    id: "tpl-4",
    name: "Treatment Follow-Up",
    type: "email",
    category: "follow-up",
    subject: "Your Treatment Plan at {{clinicName}}",
    body: "Dear {{firstName}},\n\nThank you for visiting us recently. We wanted to follow up on the treatment plan we discussed.\n\nRemaining Treatment: {{treatmentName}}\nEstimated Cost: {{treatmentCost}}\nInsurance Coverage: We can help verify your benefits\n\nDon't let this wait — early treatment often means simpler, more affordable care.\n\n[Book Your Appointment]\n\nBest regards,\n{{dentistName}}",
  },
  {
    id: "tpl-5",
    name: "Reactivation Campaign",
    type: "email",
    category: "campaign",
    subject: "A Special Offer Just for You, {{firstName}}",
    body: "Dear {{firstName}},\n\nIt's been a while since we've seen you at {{clinicName}}, and we want you to know — your dental health matters to us.\n\nAs a valued patient, we're offering you a complimentary consultation to get back on track with your care.\n\n✓ Comprehensive exam\n✓ Updated X-rays if needed\n✓ Personalized treatment plan\n\n[Claim Your Appointment]\n\nWe look forward to welcoming you back!\n\nWarmly,\n{{dentistName}} & the {{clinicName}} Team",
  },
  {
    id: "tpl-6",
    name: "Appointment Confirmation",
    type: "sms",
    category: "recall",
    subject: null,
    body: "Confirmed! Your appointment at {{clinicName}} is set for {{appointmentDate}} at {{appointmentTime}}. Reply C to confirm or R to reschedule. See you soon!",
  },
];

// --- Reports Data ---
export const reportsData = {
  revenueRecovered: [
    { month: "Jan", value: 4200 },
    { month: "Feb", value: 5800 },
    { month: "Mar", value: 6200 },
    { month: "Apr", value: 7100 },
    { month: "May", value: 8400 },
    { month: "Jun", value: 10880 },
  ],
  patientsReactivated: [
    { month: "Jan", value: 18 },
    { month: "Feb", value: 24 },
    { month: "Mar", value: 32 },
    { month: "Apr", value: 38 },
    { month: "May", value: 42 },
    { month: "Jun", value: 48 },
  ],
  appointmentsRecovered: [
    { month: "Jan", value: 14 },
    { month: "Feb", value: 22 },
    { month: "Mar", value: 28 },
    { month: "Apr", value: 32 },
    { month: "May", value: 38 },
    { month: "Jun", value: 52 },
  ],
  campaignPerformance: [
    { name: "Overdue 6+ Months", sent: 96, opened: 65, responded: 23, booked: 18 },
    { name: "Treatment Follow-Up", sent: 45, opened: 32, responded: 14, booked: 8 },
    { name: "No-Show Recovery", sent: 20, opened: 11, responded: 3, booked: 3 },
    { name: "Welcome Series", sent: 18, opened: 15, responded: 8, booked: 12 },
  ],
  noShowTrend: [
    { month: "Jan", rate: 12 },
    { month: "Feb", rate: 10 },
    { month: "Mar", rate: 9 },
    { month: "Apr", rate: 8 },
    { month: "May", rate: 7 },
    { month: "Jun", rate: 6 },
  ],
};
